// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inventory_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavigationCommand_Direction int32

const (
	NavigationCommand_UNKNOWN  NavigationCommand_Direction = 0
	NavigationCommand_LEFT     NavigationCommand_Direction = 1
	NavigationCommand_RIGHT    NavigationCommand_Direction = 2
	NavigationCommand_UP       NavigationCommand_Direction = 3
	NavigationCommand_DOWN     NavigationCommand_Direction = 4
	NavigationCommand_FORWARD  NavigationCommand_Direction = 5
	NavigationCommand_BACKWARD NavigationCommand_Direction = 6
)

// Enum value maps for NavigationCommand_Direction.
var (
	NavigationCommand_Direction_name = map[int32]string{
		0: "UNKNOWN",
		1: "LEFT",
		2: "RIGHT",
		3: "UP",
		4: "DOWN",
		5: "FORWARD",
		6: "BACKWARD",
	}
	NavigationCommand_Direction_value = map[string]int32{
		"UNKNOWN":  0,
		"LEFT":     1,
		"RIGHT":    2,
		"UP":       3,
		"DOWN":     4,
		"FORWARD":  5,
		"BACKWARD": 6,
	}
)

func (x NavigationCommand_Direction) Enum() *NavigationCommand_Direction {
	p := new(NavigationCommand_Direction)
	*p = x
	return p
}

func (x NavigationCommand_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationCommand_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[0].Descriptor()
}

func (NavigationCommand_Direction) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[0]
}

func (x NavigationCommand_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationCommand_Direction.Descriptor instead.
func (NavigationCommand_Direction) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{10, 0}
}

type ZoomCommand_ZoomType int32

const (
	ZoomCommand_IN    ZoomCommand_ZoomType = 0
	ZoomCommand_OUT   ZoomCommand_ZoomType = 1
	ZoomCommand_RESET ZoomCommand_ZoomType = 2
)

// Enum value maps for ZoomCommand_ZoomType.
var (
	ZoomCommand_ZoomType_name = map[int32]string{
		0: "IN",
		1: "OUT",
		2: "RESET",
	}
	ZoomCommand_ZoomType_value = map[string]int32{
		"IN":    0,
		"OUT":   1,
		"RESET": 2,
	}
)

func (x ZoomCommand_ZoomType) Enum() *ZoomCommand_ZoomType {
	p := new(ZoomCommand_ZoomType)
	*p = x
	return p
}

func (x ZoomCommand_ZoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoomCommand_ZoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[1].Descriptor()
}

func (ZoomCommand_ZoomType) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[1]
}

func (x ZoomCommand_ZoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoomCommand_ZoomType.Descriptor instead.
func (ZoomCommand_ZoomType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{13, 0}
}

type ApprovalStatusUpdate_Status int32

const (
	ApprovalStatusUpdate_PENDING  ApprovalStatusUpdate_Status = 0
	ApprovalStatusUpdate_APPROVED ApprovalStatusUpdate_Status = 1
	ApprovalStatusUpdate_DENIED   ApprovalStatusUpdate_Status = 2
)

// Enum value maps for ApprovalStatusUpdate_Status.
var (
	ApprovalStatusUpdate_Status_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "DENIED",
	}
	ApprovalStatusUpdate_Status_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"DENIED":   2,
	}
)

func (x ApprovalStatusUpdate_Status) Enum() *ApprovalStatusUpdate_Status {
	p := new(ApprovalStatusUpdate_Status)
	*p = x
	return p
}

func (x ApprovalStatusUpdate_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalStatusUpdate_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[2].Descriptor()
}

func (ApprovalStatusUpdate_Status) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[2]
}

func (x ApprovalStatusUpdate_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalStatusUpdate_Status.Descriptor instead.
func (ApprovalStatusUpdate_Status) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{31, 0}
}

// Session messages
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateSessionRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *JoinSessionRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_inventory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{2}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_inventory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Provider messages
type ProviderMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token     string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProviderMessage_VideoFrame
	//	*ProviderMessage_SensorData
	//	*ProviderMessage_Status
	Payload       isProviderMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMessage) Reset() {
	*x = ProviderMessage{}
	mi := &file_inventory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMessage) ProtoMessage() {}

func (x *ProviderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMessage.ProtoReflect.Descriptor instead.
func (*ProviderMessage) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProviderMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProviderMessage) GetPayload() isProviderMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProviderMessage) GetVideoFrame() *VideoFrame {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_VideoFrame); ok {
			return x.VideoFrame
		}
	}
	return nil
}

func (x *ProviderMessage) GetSensorData() *SensorData {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_SensorData); ok {
			return x.SensorData
		}
	}
	return nil
}

func (x *ProviderMessage) GetStatus() *ProviderStatus {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isProviderMessage_Payload interface {
	isProviderMessage_Payload()
}

type ProviderMessage_VideoFrame struct {
	VideoFrame *VideoFrame `protobuf:"bytes,3,opt,name=video_frame,json=videoFrame,proto3,oneof"`
}

type ProviderMessage_SensorData struct {
	SensorData *SensorData `protobuf:"bytes,4,opt,name=sensor_data,json=sensorData,proto3,oneof"`
}

type ProviderMessage_Status struct {
	Status *ProviderStatus `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

func (*ProviderMessage_VideoFrame) isProviderMessage_Payload() {}

func (*ProviderMessage_SensorData) isProviderMessage_Payload() {}

func (*ProviderMessage_Status) isProviderMessage_Payload() {}

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameData     []byte                 `protobuf:"bytes,1,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"` // JPEG encoded frame
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	IsBlurred     bool                   `protobuf:"varint,5,opt,name=is_blurred,json=isBlurred,proto3" json:"is_blurred,omitempty"` // Indicates if privacy processing is complete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_inventory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{6}
}

func (x *VideoFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *VideoFrame) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VideoFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFrame) GetIsBlurred() bool {
	if x != nil {
		return x.IsBlurred
	}
	return false
}

type SensorData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccelerometerX float32                `protobuf:"fixed32,1,opt,name=accelerometer_x,json=accelerometerX,proto3" json:"accelerometer_x,omitempty"`
	AccelerometerY float32                `protobuf:"fixed32,2,opt,name=accelerometer_y,json=accelerometerY,proto3" json:"accelerometer_y,omitempty"`
	AccelerometerZ float32                `protobuf:"fixed32,3,opt,name=accelerometer_z,json=accelerometerZ,proto3" json:"accelerometer_z,omitempty"`
	CompassHeading float32                `protobuf:"fixed32,4,opt,name=compass_heading,json=compassHeading,proto3" json:"compass_heading,omitempty"`
	GyroscopeX     float32                `protobuf:"fixed32,5,opt,name=gyroscope_x,json=gyroscopeX,proto3" json:"gyroscope_x,omitempty"`
	GyroscopeY     float32                `protobuf:"fixed32,6,opt,name=gyroscope_y,json=gyroscopeY,proto3" json:"gyroscope_y,omitempty"`
	GyroscopeZ     float32                `protobuf:"fixed32,7,opt,name=gyroscope_z,json=gyroscopeZ,proto3" json:"gyroscope_z,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_inventory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{7}
}

func (x *SensorData) GetAccelerometerX() float32 {
	if x != nil {
		return x.AccelerometerX
	}
	return 0
}

func (x *SensorData) GetAccelerometerY() float32 {
	if x != nil {
		return x.AccelerometerY
	}
	return 0
}

func (x *SensorData) GetAccelerometerZ() float32 {
	if x != nil {
		return x.AccelerometerZ
	}
	return 0
}

func (x *SensorData) GetCompassHeading() float32 {
	if x != nil {
		return x.CompassHeading
	}
	return 0
}

func (x *SensorData) GetGyroscopeX() float32 {
	if x != nil {
		return x.GyroscopeX
	}
	return 0
}

func (x *SensorData) GetGyroscopeY() float32 {
	if x != nil {
		return x.GyroscopeY
	}
	return 0
}

func (x *SensorData) GetGyroscopeZ() float32 {
	if x != nil {
		return x.GyroscopeZ
	}
	return 0
}

type ProviderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraActive  bool                   `protobuf:"varint,1,opt,name=camera_active,json=cameraActive,proto3" json:"camera_active,omitempty"`
	BatteryLevel  int32                  `protobuf:"varint,2,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_inventory_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderStatus) GetCameraActive() bool {
	if x != nil {
		return x.CameraActive
	}
	return false
}

func (x *ProviderStatus) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

// Provider receives commands from Consumer
type ProviderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ProviderCommand_Navigation
	//	*ProviderCommand_Laser
	//	*ProviderCommand_Stop
	//	*ProviderCommand_Zoom
	Command       isProviderCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCommand) Reset() {
	*x = ProviderCommand{}
	mi := &file_inventory_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCommand) ProtoMessage() {}

func (x *ProviderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCommand.ProtoReflect.Descriptor instead.
func (*ProviderCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderCommand) GetCommand() isProviderCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProviderCommand) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *ProviderCommand) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *ProviderCommand) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ProviderCommand) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

type isProviderCommand_Command interface {
	isProviderCommand_Command()
}

type ProviderCommand_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,1,opt,name=navigation,proto3,oneof"`
}

type ProviderCommand_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,2,opt,name=laser,proto3,oneof"`
}

type ProviderCommand_Stop struct {
	Stop *StopCommand `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type ProviderCommand_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,4,opt,name=zoom,proto3,oneof"`
}

func (*ProviderCommand_Navigation) isProviderCommand_Command() {}

func (*ProviderCommand_Laser) isProviderCommand_Command() {}

func (*ProviderCommand_Stop) isProviderCommand_Command() {}

func (*ProviderCommand_Zoom) isProviderCommand_Command() {}

type NavigationCommand struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Direction     NavigationCommand_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=inventory.NavigationCommand_Direction" json:"direction,omitempty"`
	Intensity     float32                     `protobuf:"fixed32,2,opt,name=intensity,proto3" json:"intensity,omitempty"` // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationCommand) Reset() {
	*x = NavigationCommand{}
	mi := &file_inventory_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationCommand) ProtoMessage() {}

func (x *NavigationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationCommand.ProtoReflect.Descriptor instead.
func (*NavigationCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{10}
}

func (x *NavigationCommand) GetDirection() NavigationCommand_Direction {
	if x != nil {
		return x.Direction
	}
	return NavigationCommand_UNKNOWN
}

func (x *NavigationCommand) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type LaserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ScreenX       float32                `protobuf:"fixed32,2,opt,name=screen_x,json=screenX,proto3" json:"screen_x,omitempty"` // Normalized 0.0 to 1.0
	ScreenY       float32                `protobuf:"fixed32,3,opt,name=screen_y,json=screenY,proto3" json:"screen_y,omitempty"` // Normalized 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaserCommand) Reset() {
	*x = LaserCommand{}
	mi := &file_inventory_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaserCommand) ProtoMessage() {}

func (x *LaserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaserCommand.ProtoReflect.Descriptor instead.
func (*LaserCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{11}
}

func (x *LaserCommand) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LaserCommand) GetScreenX() float32 {
	if x != nil {
		return x.ScreenX
	}
	return 0
}

func (x *LaserCommand) GetScreenY() float32 {
	if x != nil {
		return x.ScreenY
	}
	return 0
}

type StopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emergency     bool                   `protobuf:"varint,1,opt,name=emergency,proto3" json:"emergency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCommand) Reset() {
	*x = StopCommand{}
	mi := &file_inventory_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCommand) ProtoMessage() {}

func (x *StopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCommand.ProtoReflect.Descriptor instead.
func (*StopCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{12}
}

func (x *StopCommand) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

type ZoomCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ZoomCommand_ZoomType   `protobuf:"varint,1,opt,name=type,proto3,enum=inventory.ZoomCommand_ZoomType" json:"type,omitempty"`
	Level         float32                `protobuf:"fixed32,2,opt,name=level,proto3" json:"level,omitempty"` // Current zoom level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoomCommand) Reset() {
	*x = ZoomCommand{}
	mi := &file_inventory_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoomCommand) ProtoMessage() {}

func (x *ZoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoomCommand.ProtoReflect.Descriptor instead.
func (*ZoomCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{13}
}

func (x *ZoomCommand) GetType() ZoomCommand_ZoomType {
	if x != nil {
		return x.Type
	}
	return ZoomCommand_IN
}

func (x *ZoomCommand) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Consumer messages
type ConsumerCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token     string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ConsumerCommand_Navigation
	//	*ConsumerCommand_Laser
	//	*ConsumerCommand_Stop
	//	*ConsumerCommand_Zoom
	//	*ConsumerCommand_Voice
	//	*ConsumerCommand_Text
	Command       isConsumerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerCommand) Reset() {
	*x = ConsumerCommand{}
	mi := &file_inventory_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerCommand) ProtoMessage() {}

func (x *ConsumerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerCommand.ProtoReflect.Descriptor instead.
func (*ConsumerCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{14}
}

func (x *ConsumerCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsumerCommand) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsumerCommand) GetCommand() isConsumerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ConsumerCommand) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *ConsumerCommand) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *ConsumerCommand) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ConsumerCommand) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

func (x *ConsumerCommand) GetVoice() *VoiceCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *ConsumerCommand) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isConsumerCommand_Command interface {
	isConsumerCommand_Command()
}

type ConsumerCommand_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,3,opt,name=navigation,proto3,oneof"`
}

type ConsumerCommand_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,4,opt,name=laser,proto3,oneof"`
}

type ConsumerCommand_Stop struct {
	Stop *StopCommand `protobuf:"bytes,5,opt,name=stop,proto3,oneof"`
}

type ConsumerCommand_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,6,opt,name=zoom,proto3,oneof"`
}

type ConsumerCommand_Voice struct {
	Voice *VoiceCommand `protobuf:"bytes,7,opt,name=voice,proto3,oneof"`
}

type ConsumerCommand_Text struct {
	Text *TextCommand `protobuf:"bytes,8,opt,name=text,proto3,oneof"`
}

func (*ConsumerCommand_Navigation) isConsumerCommand_Command() {}

func (*ConsumerCommand_Laser) isConsumerCommand_Command() {}

func (*ConsumerCommand_Stop) isConsumerCommand_Command() {}

func (*ConsumerCommand_Zoom) isConsumerCommand_Command() {}

func (*ConsumerCommand_Voice) isConsumerCommand_Command() {}

func (*ConsumerCommand_Text) isConsumerCommand_Command() {}

type VoiceCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TranscribedText string                 `protobuf:"bytes,1,opt,name=transcribed_text,json=transcribedText,proto3" json:"transcribed_text,omitempty"`
	Confidence      float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoiceCommand) Reset() {
	*x = VoiceCommand{}
	mi := &file_inventory_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCommand) ProtoMessage() {}

func (x *VoiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCommand.ProtoReflect.Descriptor instead.
func (*VoiceCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{15}
}

func (x *VoiceCommand) GetTranscribedText() string {
	if x != nil {
		return x.TranscribedText
	}
	return ""
}

func (x *VoiceCommand) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type TextCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCommand) Reset() {
	*x = TextCommand{}
	mi := &file_inventory_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCommand) ProtoMessage() {}

func (x *TextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCommand.ProtoReflect.Descriptor instead.
func (*TextCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{16}
}

func (x *TextCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "provider" or "consumer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_inventory_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Active            bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	SessionDurationMs int64                  `protobuf:"varint,2,opt,name=session_duration_ms,json=sessionDurationMs,proto3" json:"session_duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_inventory_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HeartbeatResponse) GetSessionDurationMs() int64 {
	if x != nil {
		return x.SessionDurationMs
	}
	return 0
}

// Session Discovery Messages
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_inventory_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_inventory_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProviderName         string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderLocation     string                 `protobuf:"bytes,3,opt,name=provider_location,json=providerLocation,proto3" json:"provider_location,omitempty"`
	CreatedAt            int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AcceptingConnections bool                   `protobuf:"varint,5,opt,name=accepting_connections,json=acceptingConnections,proto3" json:"accepting_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_inventory_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{21}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SessionInfo) GetProviderLocation() string {
	if x != nil {
		return x.ProviderLocation
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetAcceptingConnections() bool {
	if x != nil {
		return x.AcceptingConnections
	}
	return false
}

// Connection Request Messages
type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_inventory_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{22}
}

func (x *ConnectionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConnectionRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_inventory_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{23}
}

func (x *ConnectionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequestsRequest) Reset() {
	*x = WatchRequestsRequest{}
	mi := &file_inventory_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequestsRequest) ProtoMessage() {}

func (x *WatchRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequestsRequest.ProtoReflect.Descriptor instead.
func (*WatchRequestsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{24}
}

func (x *WatchRequestsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConnectionRequestNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequestNotification) Reset() {
	*x = ConnectionRequestNotification{}
	mi := &file_inventory_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequestNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequestNotification) ProtoMessage() {}

func (x *ConnectionRequestNotification) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequestNotification.ProtoReflect.Descriptor instead.
func (*ConnectionRequestNotification) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{25}
}

func (x *ConnectionRequestNotification) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectionRequestNotification) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConnectionRequestNotification) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ConnectionRequestNotification) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

// Approval Messages
type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_inventory_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{26}
}

func (x *ApproveRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_inventory_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{27}
}

func (x *ApproveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApproveResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequest) Reset() {
	*x = DenyRequest{}
	mi := &file_inventory_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequest) ProtoMessage() {}

func (x *DenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequest.ProtoReflect.Descriptor instead.
func (*DenyRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{28}
}

func (x *DenyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	mi := &file_inventory_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{29}
}

func (x *DenyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchApprovalRequest) Reset() {
	*x = WatchApprovalRequest{}
	mi := &file_inventory_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchApprovalRequest) ProtoMessage() {}

func (x *WatchApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchApprovalRequest.ProtoReflect.Descriptor instead.
func (*WatchApprovalRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{30}
}

func (x *WatchApprovalRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApprovalStatusUpdate struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        ApprovalStatusUpdate_Status `protobuf:"varint,1,opt,name=status,proto3,enum=inventory.ApprovalStatusUpdate_Status" json:"status,omitempty"`
	SessionId     string                      `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStatusUpdate) Reset() {
	*x = ApprovalStatusUpdate{}
	mi := &file_inventory_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStatusUpdate) ProtoMessage() {}

func (x *ApprovalStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStatusUpdate.ProtoReflect.Descriptor instead.
func (*ApprovalStatusUpdate) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{31}
}

func (x *ApprovalStatusUpdate) GetStatus() ApprovalStatusUpdate_Status {
	if x != nil {
		return x.Status
	}
	return ApprovalStatusUpdate_PENDING
}

func (x *ApprovalStatusUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApprovalStatusUpdate) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApprovalStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Command Messages
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to CommandType:
	//
	//	*Command_Navigation
	//	*Command_Laser
	//	*Command_Stop
	//	*Command_Zoom
	//	*Command_Voice
	//	*Command_Text
	CommandType   isCommand_CommandType `protobuf_oneof:"command_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_inventory_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{32}
}

func (x *Command) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Command) GetCommandType() isCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return nil
}

func (x *Command) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *Command) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *Command) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

func (x *Command) GetVoice() *VoiceCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *Command) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isCommand_CommandType interface {
	isCommand_CommandType()
}

type Command_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,2,opt,name=navigation,proto3,oneof"`
}

type Command_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,3,opt,name=laser,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopCommand `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type Command_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,5,opt,name=zoom,proto3,oneof"`
}

type Command_Voice struct {
	Voice *VoiceCommand `protobuf:"bytes,6,opt,name=voice,proto3,oneof"`
}

type Command_Text struct {
	Text *TextCommand `protobuf:"bytes,7,opt,name=text,proto3,oneof"`
}

func (*Command_Navigation) isCommand_CommandType() {}

func (*Command_Laser) isCommand_CommandType() {}

func (*Command_Stop) isCommand_CommandType() {}

func (*Command_Zoom) isCommand_CommandType() {}

func (*Command_Voice) isCommand_CommandType() {}

func (*Command_Text) isCommand_CommandType() {}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_inventory_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{33}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inventory_service_proto protoreflect.FileDescriptor

const file_inventory_service_proto_rawDesc = "" +
	"\n" +
	"\x17inventory_service.proto\x12\tinventory\x1a\x1cgoogle/api/annotations.proto\"\\\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\"y\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\"z\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"H\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\".\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xfa\x01\n" +
	"\x0fProviderMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x128\n" +
	"\vvideo_frame\x18\x03 \x01(\v2\x15.inventory.VideoFrameH\x00R\n" +
	"videoFrame\x128\n" +
	"\vsensor_data\x18\x04 \x01(\v2\x15.inventory.SensorDataH\x00R\n" +
	"sensorData\x123\n" +
	"\x06status\x18\x05 \x01(\v2\x19.inventory.ProviderStatusH\x00R\x06statusB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\n" +
	"VideoFrame\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x01 \x01(\fR\tframeData\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"is_blurred\x18\x05 \x01(\bR\tisBlurred\"\x93\x02\n" +
	"\n" +
	"SensorData\x12'\n" +
	"\x0faccelerometer_x\x18\x01 \x01(\x02R\x0eaccelerometerX\x12'\n" +
	"\x0faccelerometer_y\x18\x02 \x01(\x02R\x0eaccelerometerY\x12'\n" +
	"\x0faccelerometer_z\x18\x03 \x01(\x02R\x0eaccelerometerZ\x12'\n" +
	"\x0fcompass_heading\x18\x04 \x01(\x02R\x0ecompassHeading\x12\x1f\n" +
	"\vgyroscope_x\x18\x05 \x01(\x02R\n" +
	"gyroscopeX\x12\x1f\n" +
	"\vgyroscope_y\x18\x06 \x01(\x02R\n" +
	"gyroscopeY\x12\x1f\n" +
	"\vgyroscope_z\x18\a \x01(\x02R\n" +
	"gyroscopeZ\"Z\n" +
	"\x0eProviderStatus\x12#\n" +
	"\rcamera_active\x18\x01 \x01(\bR\fcameraActive\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x05R\fbatteryLevel\"\xe9\x01\n" +
	"\x0fProviderCommand\x12>\n" +
	"\n" +
	"navigation\x18\x01 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x02 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x03 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x04 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoomB\t\n" +
	"\acommand\"\xd3\x01\n" +
	"\x11NavigationCommand\x12D\n" +
	"\tdirection\x18\x01 \x01(\x0e2&.inventory.NavigationCommand.DirectionR\tdirection\x12\x1c\n" +
	"\tintensity\x18\x02 \x01(\x02R\tintensity\"Z\n" +
	"\tDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\x06\n" +
	"\x02UP\x10\x03\x12\b\n" +
	"\x04DOWN\x10\x04\x12\v\n" +
	"\aFORWARD\x10\x05\x12\f\n" +
	"\bBACKWARD\x10\x06\"\\\n" +
	"\fLaserCommand\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x19\n" +
	"\bscreen_x\x18\x02 \x01(\x02R\ascreenX\x12\x19\n" +
	"\bscreen_y\x18\x03 \x01(\x02R\ascreenY\"+\n" +
	"\vStopCommand\x12\x1c\n" +
	"\temergency\x18\x01 \x01(\bR\temergency\"\x80\x01\n" +
	"\vZoomCommand\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.inventory.ZoomCommand.ZoomTypeR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x02R\x05level\"&\n" +
	"\bZoomType\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03OUT\x10\x01\x12\t\n" +
	"\x05RESET\x10\x02\"\xfd\x02\n" +
	"\x0fConsumerCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12>\n" +
	"\n" +
	"navigation\x18\x03 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x04 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x05 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x06 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoom\x12/\n" +
	"\x05voice\x18\a \x01(\v2\x17.inventory.VoiceCommandH\x00R\x05voice\x12,\n" +
	"\x04text\x18\b \x01(\v2\x16.inventory.TextCommandH\x00R\x04textB\t\n" +
	"\acommand\"Y\n" +
	"\fVoiceCommand\x12)\n" +
	"\x10transcribed_text\x18\x01 \x01(\tR\x0ftranscribedText\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"!\n" +
	"\vTextCommand\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"[\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"[\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12.\n" +
	"\x13session_duration_ms\x18\x02 \x01(\x03R\x11sessionDurationMs\"8\n" +
	"\x13ListSessionsRequest\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\"J\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.inventory.SessionInfoR\bsessions\"\xd2\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12+\n" +
	"\x11provider_location\x18\x03 \x01(\tR\x10providerLocation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x123\n" +
	"\x15accepting_connections\x18\x05 \x01(\bR\x14acceptingConnections\"x\n" +
	"\x11ConnectionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\"g\n" +
	"\x12ConnectionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"5\n" +
	"\x14WatchRequestsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa7\x01\n" +
	"\x1dConnectionRequestNotification\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12!\n" +
	"\frequested_at\x18\x04 \x01(\x03R\vrequestedAt\"/\n" +
	"\x0eApproveRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"`\n" +
	"\x0fApproveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"D\n" +
	"\vDenyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"(\n" +
	"\fDenyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14WatchApprovalRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xd6\x01\n" +
	"\x14ApprovalStatusUpdate\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.inventory.ApprovalStatusUpdate.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\n" +
	"\n" +
	"\x06DENIED\x10\x02\"\xe4\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\n" +
	"navigation\x18\x02 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x03 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x04 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x05 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoom\x12/\n" +
	"\x05voice\x18\x06 \x01(\v2\x17.inventory.VoiceCommandH\x00R\x05voice\x12,\n" +
	"\x04text\x18\a \x01(\v2\x16.inventory.TextCommandH\x00R\x04textB\x0e\n" +
	"\fcommand_type\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc3\n" +
	"\n" +
	"\x16RemoteInventoryService\x12e\n" +
	"\rCreateSession\x12\x1f.inventory.CreateSessionRequest\x1a\x1a.inventory.SessionResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12e\n" +
	"\fListSessions\x12\x1e.inventory.ListSessionsRequest\x1a\x1f.inventory.ListSessionsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/sessions\x12~\n" +
	"\x11RequestConnection\x12\x1c.inventory.ConnectionRequest\x1a\x1d.inventory.ConnectionResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/sessions/{session_id}/connect\x12h\n" +
	"\x17WatchConnectionRequests\x12\x1f.inventory.WatchRequestsRequest\x1a(.inventory.ConnectionRequestNotification\"\x000\x01\x12x\n" +
	"\x11ApproveConnection\x12\x19.inventory.ApproveRequest\x1a\x1a.inventory.ApproveResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/requests/{request_id}/approve\x12l\n" +
	"\x0eDenyConnection\x12\x16.inventory.DenyRequest\x1a\x17.inventory.DenyResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/requests/{request_id}/deny\x12[\n" +
	"\x13WatchApprovalStatus\x12\x1f.inventory.WatchApprovalRequest\x1a\x1f.inventory.ApprovalStatusUpdate\"\x000\x01\x12A\n" +
	"\vStreamVideo\x12\x15.inventory.VideoFrame\x1a\x15.inventory.VideoFrame\"\x00(\x010\x01\x12l\n" +
	"\vSendCommand\x12\x12.inventory.Command\x1a\x1a.inventory.CommandResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/sessions/{session_id}/commands\x12l\n" +
	"\n" +
	"EndSession\x12\x1c.inventory.EndSessionRequest\x1a\x1d.inventory.EndSessionResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/sessions/{session_id}\x12L\n" +
	"\x0eProviderStream\x12\x1a.inventory.ProviderMessage\x1a\x1a.inventory.ProviderCommand(\x010\x01\x12G\n" +
	"\x0eConsumerStream\x12\x1a.inventory.ConsumerCommand\x1a\x15.inventory.VideoFrame(\x010\x01\x12v\n" +
	"\tHeartbeat\x12\x1b.inventory.HeartbeatRequest\x1a\x1c.inventory.HeartbeatResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/sessions/{session_id}/heartbeatB*Z(github.com/djgupt/remote-inventory/protob\x06proto3"

var (
	file_inventory_service_proto_rawDescOnce sync.Once
	file_inventory_service_proto_rawDescData []byte
)

func file_inventory_service_proto_rawDescGZIP() []byte {
	file_inventory_service_proto_rawDescOnce.Do(func() {
		file_inventory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)))
	})
	return file_inventory_service_proto_rawDescData
}

var file_inventory_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_inventory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_inventory_service_proto_goTypes = []any{
	(NavigationCommand_Direction)(0),      // 0: inventory.NavigationCommand.Direction
	(ZoomCommand_ZoomType)(0),             // 1: inventory.ZoomCommand.ZoomType
	(ApprovalStatusUpdate_Status)(0),      // 2: inventory.ApprovalStatusUpdate.Status
	(*CreateSessionRequest)(nil),          // 3: inventory.CreateSessionRequest
	(*JoinSessionRequest)(nil),            // 4: inventory.JoinSessionRequest
	(*SessionResponse)(nil),               // 5: inventory.SessionResponse
	(*EndSessionRequest)(nil),             // 6: inventory.EndSessionRequest
	(*EndSessionResponse)(nil),            // 7: inventory.EndSessionResponse
	(*ProviderMessage)(nil),               // 8: inventory.ProviderMessage
	(*VideoFrame)(nil),                    // 9: inventory.VideoFrame
	(*SensorData)(nil),                    // 10: inventory.SensorData
	(*ProviderStatus)(nil),                // 11: inventory.ProviderStatus
	(*ProviderCommand)(nil),               // 12: inventory.ProviderCommand
	(*NavigationCommand)(nil),             // 13: inventory.NavigationCommand
	(*LaserCommand)(nil),                  // 14: inventory.LaserCommand
	(*StopCommand)(nil),                   // 15: inventory.StopCommand
	(*ZoomCommand)(nil),                   // 16: inventory.ZoomCommand
	(*ConsumerCommand)(nil),               // 17: inventory.ConsumerCommand
	(*VoiceCommand)(nil),                  // 18: inventory.VoiceCommand
	(*TextCommand)(nil),                   // 19: inventory.TextCommand
	(*HeartbeatRequest)(nil),              // 20: inventory.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 21: inventory.HeartbeatResponse
	(*ListSessionsRequest)(nil),           // 22: inventory.ListSessionsRequest
	(*ListSessionsResponse)(nil),          // 23: inventory.ListSessionsResponse
	(*SessionInfo)(nil),                   // 24: inventory.SessionInfo
	(*ConnectionRequest)(nil),             // 25: inventory.ConnectionRequest
	(*ConnectionResponse)(nil),            // 26: inventory.ConnectionResponse
	(*WatchRequestsRequest)(nil),          // 27: inventory.WatchRequestsRequest
	(*ConnectionRequestNotification)(nil), // 28: inventory.ConnectionRequestNotification
	(*ApproveRequest)(nil),                // 29: inventory.ApproveRequest
	(*ApproveResponse)(nil),               // 30: inventory.ApproveResponse
	(*DenyRequest)(nil),                   // 31: inventory.DenyRequest
	(*DenyResponse)(nil),                  // 32: inventory.DenyResponse
	(*WatchApprovalRequest)(nil),          // 33: inventory.WatchApprovalRequest
	(*ApprovalStatusUpdate)(nil),          // 34: inventory.ApprovalStatusUpdate
	(*Command)(nil),                       // 35: inventory.Command
	(*CommandResponse)(nil),               // 36: inventory.CommandResponse
}
var file_inventory_service_proto_depIdxs = []int32{
	9,  // 0: inventory.ProviderMessage.video_frame:type_name -> inventory.VideoFrame
	10, // 1: inventory.ProviderMessage.sensor_data:type_name -> inventory.SensorData
	11, // 2: inventory.ProviderMessage.status:type_name -> inventory.ProviderStatus
	13, // 3: inventory.ProviderCommand.navigation:type_name -> inventory.NavigationCommand
	14, // 4: inventory.ProviderCommand.laser:type_name -> inventory.LaserCommand
	15, // 5: inventory.ProviderCommand.stop:type_name -> inventory.StopCommand
	16, // 6: inventory.ProviderCommand.zoom:type_name -> inventory.ZoomCommand
	0,  // 7: inventory.NavigationCommand.direction:type_name -> inventory.NavigationCommand.Direction
	1,  // 8: inventory.ZoomCommand.type:type_name -> inventory.ZoomCommand.ZoomType
	13, // 9: inventory.ConsumerCommand.navigation:type_name -> inventory.NavigationCommand
	14, // 10: inventory.ConsumerCommand.laser:type_name -> inventory.LaserCommand
	15, // 11: inventory.ConsumerCommand.stop:type_name -> inventory.StopCommand
	16, // 12: inventory.ConsumerCommand.zoom:type_name -> inventory.ZoomCommand
	18, // 13: inventory.ConsumerCommand.voice:type_name -> inventory.VoiceCommand
	19, // 14: inventory.ConsumerCommand.text:type_name -> inventory.TextCommand
	24, // 15: inventory.ListSessionsResponse.sessions:type_name -> inventory.SessionInfo
	2,  // 16: inventory.ApprovalStatusUpdate.status:type_name -> inventory.ApprovalStatusUpdate.Status
	13, // 17: inventory.Command.navigation:type_name -> inventory.NavigationCommand
	14, // 18: inventory.Command.laser:type_name -> inventory.LaserCommand
	15, // 19: inventory.Command.stop:type_name -> inventory.StopCommand
	16, // 20: inventory.Command.zoom:type_name -> inventory.ZoomCommand
	18, // 21: inventory.Command.voice:type_name -> inventory.VoiceCommand
	19, // 22: inventory.Command.text:type_name -> inventory.TextCommand
	3,  // 23: inventory.RemoteInventoryService.CreateSession:input_type -> inventory.CreateSessionRequest
	22, // 24: inventory.RemoteInventoryService.ListSessions:input_type -> inventory.ListSessionsRequest
	25, // 25: inventory.RemoteInventoryService.RequestConnection:input_type -> inventory.ConnectionRequest
	27, // 26: inventory.RemoteInventoryService.WatchConnectionRequests:input_type -> inventory.WatchRequestsRequest
	29, // 27: inventory.RemoteInventoryService.ApproveConnection:input_type -> inventory.ApproveRequest
	31, // 28: inventory.RemoteInventoryService.DenyConnection:input_type -> inventory.DenyRequest
	33, // 29: inventory.RemoteInventoryService.WatchApprovalStatus:input_type -> inventory.WatchApprovalRequest
	9,  // 30: inventory.RemoteInventoryService.StreamVideo:input_type -> inventory.VideoFrame
	35, // 31: inventory.RemoteInventoryService.SendCommand:input_type -> inventory.Command
	6,  // 32: inventory.RemoteInventoryService.EndSession:input_type -> inventory.EndSessionRequest
	8,  // 33: inventory.RemoteInventoryService.ProviderStream:input_type -> inventory.ProviderMessage
	17, // 34: inventory.RemoteInventoryService.ConsumerStream:input_type -> inventory.ConsumerCommand
	20, // 35: inventory.RemoteInventoryService.Heartbeat:input_type -> inventory.HeartbeatRequest
	5,  // 36: inventory.RemoteInventoryService.CreateSession:output_type -> inventory.SessionResponse
	23, // 37: inventory.RemoteInventoryService.ListSessions:output_type -> inventory.ListSessionsResponse
	26, // 38: inventory.RemoteInventoryService.RequestConnection:output_type -> inventory.ConnectionResponse
	28, // 39: inventory.RemoteInventoryService.WatchConnectionRequests:output_type -> inventory.ConnectionRequestNotification
	30, // 40: inventory.RemoteInventoryService.ApproveConnection:output_type -> inventory.ApproveResponse
	32, // 41: inventory.RemoteInventoryService.DenyConnection:output_type -> inventory.DenyResponse
	34, // 42: inventory.RemoteInventoryService.WatchApprovalStatus:output_type -> inventory.ApprovalStatusUpdate
	9,  // 43: inventory.RemoteInventoryService.StreamVideo:output_type -> inventory.VideoFrame
	36, // 44: inventory.RemoteInventoryService.SendCommand:output_type -> inventory.CommandResponse
	7,  // 45: inventory.RemoteInventoryService.EndSession:output_type -> inventory.EndSessionResponse
	12, // 46: inventory.RemoteInventoryService.ProviderStream:output_type -> inventory.ProviderCommand
	9,  // 47: inventory.RemoteInventoryService.ConsumerStream:output_type -> inventory.VideoFrame
	21, // 48: inventory.RemoteInventoryService.Heartbeat:output_type -> inventory.HeartbeatResponse
	36, // [36:49] is the sub-list for method output_type
	23, // [23:36] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_inventory_service_proto_init() }
func file_inventory_service_proto_init() {
	if File_inventory_service_proto != nil {
		return
	}
	file_inventory_service_proto_msgTypes[5].OneofWrappers = []any{
		(*ProviderMessage_VideoFrame)(nil),
		(*ProviderMessage_SensorData)(nil),
		(*ProviderMessage_Status)(nil),
	}
	file_inventory_service_proto_msgTypes[9].OneofWrappers = []any{
		(*ProviderCommand_Navigation)(nil),
		(*ProviderCommand_Laser)(nil),
		(*ProviderCommand_Stop)(nil),
		(*ProviderCommand_Zoom)(nil),
	}
	file_inventory_service_proto_msgTypes[14].OneofWrappers = []any{
		(*ConsumerCommand_Navigation)(nil),
		(*ConsumerCommand_Laser)(nil),
		(*ConsumerCommand_Stop)(nil),
		(*ConsumerCommand_Zoom)(nil),
		(*ConsumerCommand_Voice)(nil),
		(*ConsumerCommand_Text)(nil),
	}
	file_inventory_service_proto_msgTypes[32].OneofWrappers = []any{
		(*Command_Navigation)(nil),
		(*Command_Laser)(nil),
		(*Command_Stop)(nil),
		(*Command_Zoom)(nil),
		(*Command_Voice)(nil),
		(*Command_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_proto_goTypes,
		DependencyIndexes: file_inventory_service_proto_depIdxs,
		EnumInfos:         file_inventory_service_proto_enumTypes,
		MessageInfos:      file_inventory_service_proto_msgTypes,
	}.Build()
	File_inventory_service_proto = out.File
	file_inventory_service_proto_goTypes = nil
	file_inventory_service_proto_depIdxs = nil
}
