// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: inventory_service.proto

package remote_inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateSession_FullMethodName           = "/inventory.InventoryService/CreateSession"
	InventoryService_ListSessions_FullMethodName            = "/inventory.InventoryService/ListSessions"
	InventoryService_EndSession_FullMethodName              = "/inventory.InventoryService/EndSession"
	InventoryService_SendWebRTCSignal_FullMethodName        = "/inventory.InventoryService/SendWebRTCSignal"
	InventoryService_WatchWebRTCSignals_FullMethodName      = "/inventory.InventoryService/WatchWebRTCSignals"
	InventoryService_ProviderStream_FullMethodName          = "/inventory.InventoryService/ProviderStream"
	InventoryService_ConsumerStream_FullMethodName          = "/inventory.InventoryService/ConsumerStream"
	InventoryService_Heartbeat_FullMethodName               = "/inventory.InventoryService/Heartbeat"
	InventoryService_RequestConnection_FullMethodName       = "/inventory.InventoryService/RequestConnection"
	InventoryService_ApproveConnection_FullMethodName       = "/inventory.InventoryService/ApproveConnection"
	InventoryService_DenyConnection_FullMethodName          = "/inventory.InventoryService/DenyConnection"
	InventoryService_WatchConnectionRequests_FullMethodName = "/inventory.InventoryService/WatchConnectionRequests"
	InventoryService_WatchApprovalStatus_FullMethodName     = "/inventory.InventoryService/WatchApprovalStatus"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Session management and video streaming service
type InventoryServiceClient interface {
	// Create a new session for a provider
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// List all active sessions (for consumers to discover providers)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// End a session
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	// WebRTC Signaling
	SendWebRTCSignal(ctx context.Context, in *WebRTCSignal, opts ...grpc.CallOption) (*SignalResponse, error)
	WatchWebRTCSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WebRTCSignal], error)
	// Provider streams video to Backend
	ProviderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProviderMessage, ProviderCommand], error)
	// Consumer receives privacy-blurred video and sends commands
	ConsumerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumerCommand, VideoFrame], error)
	// Heartbeat to keep session alive
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Connection Request Flow (v1.3.0)
	RequestConnection(ctx context.Context, in *RequestConnectionRequest, opts ...grpc.CallOption) (*RequestConnectionResponse, error)
	ApproveConnection(ctx context.Context, in *ApproveConnectionRequest, opts ...grpc.CallOption) (*ApproveConnectionResponse, error)
	DenyConnection(ctx context.Context, in *DenyConnectionRequest, opts ...grpc.CallOption) (*DenyConnectionResponse, error)
	WatchConnectionRequests(ctx context.Context, in *WatchConnectionRequestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionRequestNotification], error)
	WatchApprovalStatus(ctx context.Context, in *WatchApprovalStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalStatusUpdate], error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, InventoryService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) SendWebRTCSignal(ctx context.Context, in *WebRTCSignal, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, InventoryService_SendWebRTCSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) WatchWebRTCSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WebRTCSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[0], InventoryService_WatchWebRTCSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSignalsRequest, WebRTCSignal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchWebRTCSignalsClient = grpc.ServerStreamingClient[WebRTCSignal]

func (c *inventoryServiceClient) ProviderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProviderMessage, ProviderCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[1], InventoryService_ProviderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProviderMessage, ProviderCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ProviderStreamClient = grpc.BidiStreamingClient[ProviderMessage, ProviderCommand]

func (c *inventoryServiceClient) ConsumerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumerCommand, VideoFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[2], InventoryService_ConsumerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumerCommand, VideoFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ConsumerStreamClient = grpc.BidiStreamingClient[ConsumerCommand, VideoFrame]

func (c *inventoryServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, InventoryService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RequestConnection(ctx context.Context, in *RequestConnectionRequest, opts ...grpc.CallOption) (*RequestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestConnectionResponse)
	err := c.cc.Invoke(ctx, InventoryService_RequestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ApproveConnection(ctx context.Context, in *ApproveConnectionRequest, opts ...grpc.CallOption) (*ApproveConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveConnectionResponse)
	err := c.cc.Invoke(ctx, InventoryService_ApproveConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DenyConnection(ctx context.Context, in *DenyConnectionRequest, opts ...grpc.CallOption) (*DenyConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyConnectionResponse)
	err := c.cc.Invoke(ctx, InventoryService_DenyConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) WatchConnectionRequests(ctx context.Context, in *WatchConnectionRequestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionRequestNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[3], InventoryService_WatchConnectionRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConnectionRequestsRequest, ConnectionRequestNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchConnectionRequestsClient = grpc.ServerStreamingClient[ConnectionRequestNotification]

func (c *inventoryServiceClient) WatchApprovalStatus(ctx context.Context, in *WatchApprovalStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[4], InventoryService_WatchApprovalStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchApprovalStatusRequest, ApprovalStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchApprovalStatusClient = grpc.ServerStreamingClient[ApprovalStatusUpdate]

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// Session management and video streaming service
type InventoryServiceServer interface {
	// Create a new session for a provider
	CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error)
	// List all active sessions (for consumers to discover providers)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// End a session
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	// WebRTC Signaling
	SendWebRTCSignal(context.Context, *WebRTCSignal) (*SignalResponse, error)
	WatchWebRTCSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[WebRTCSignal]) error
	// Provider streams video to Backend
	ProviderStream(grpc.BidiStreamingServer[ProviderMessage, ProviderCommand]) error
	// Consumer receives privacy-blurred video and sends commands
	ConsumerStream(grpc.BidiStreamingServer[ConsumerCommand, VideoFrame]) error
	// Heartbeat to keep session alive
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Connection Request Flow (v1.3.0)
	RequestConnection(context.Context, *RequestConnectionRequest) (*RequestConnectionResponse, error)
	ApproveConnection(context.Context, *ApproveConnectionRequest) (*ApproveConnectionResponse, error)
	DenyConnection(context.Context, *DenyConnectionRequest) (*DenyConnectionResponse, error)
	WatchConnectionRequests(*WatchConnectionRequestsRequest, grpc.ServerStreamingServer[ConnectionRequestNotification]) error
	WatchApprovalStatus(*WatchApprovalStatusRequest, grpc.ServerStreamingServer[ApprovalStatusUpdate]) error
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedInventoryServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedInventoryServiceServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedInventoryServiceServer) SendWebRTCSignal(context.Context, *WebRTCSignal) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebRTCSignal not implemented")
}
func (UnimplementedInventoryServiceServer) WatchWebRTCSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[WebRTCSignal]) error {
	return status.Error(codes.Unimplemented, "method WatchWebRTCSignals not implemented")
}
func (UnimplementedInventoryServiceServer) ProviderStream(grpc.BidiStreamingServer[ProviderMessage, ProviderCommand]) error {
	return status.Error(codes.Unimplemented, "method ProviderStream not implemented")
}
func (UnimplementedInventoryServiceServer) ConsumerStream(grpc.BidiStreamingServer[ConsumerCommand, VideoFrame]) error {
	return status.Error(codes.Unimplemented, "method ConsumerStream not implemented")
}
func (UnimplementedInventoryServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedInventoryServiceServer) RequestConnection(context.Context, *RequestConnectionRequest) (*RequestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestConnection not implemented")
}
func (UnimplementedInventoryServiceServer) ApproveConnection(context.Context, *ApproveConnectionRequest) (*ApproveConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveConnection not implemented")
}
func (UnimplementedInventoryServiceServer) DenyConnection(context.Context, *DenyConnectionRequest) (*DenyConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DenyConnection not implemented")
}
func (UnimplementedInventoryServiceServer) WatchConnectionRequests(*WatchConnectionRequestsRequest, grpc.ServerStreamingServer[ConnectionRequestNotification]) error {
	return status.Error(codes.Unimplemented, "method WatchConnectionRequests not implemented")
}
func (UnimplementedInventoryServiceServer) WatchApprovalStatus(*WatchApprovalStatusRequest, grpc.ServerStreamingServer[ApprovalStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchApprovalStatus not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_SendWebRTCSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRTCSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).SendWebRTCSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_SendWebRTCSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).SendWebRTCSignal(ctx, req.(*WebRTCSignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_WatchWebRTCSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSignalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).WatchWebRTCSignals(m, &grpc.GenericServerStream[WatchSignalsRequest, WebRTCSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchWebRTCSignalsServer = grpc.ServerStreamingServer[WebRTCSignal]

func _InventoryService_ProviderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InventoryServiceServer).ProviderStream(&grpc.GenericServerStream[ProviderMessage, ProviderCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ProviderStreamServer = grpc.BidiStreamingServer[ProviderMessage, ProviderCommand]

func _InventoryService_ConsumerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InventoryServiceServer).ConsumerStream(&grpc.GenericServerStream[ConsumerCommand, VideoFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ConsumerStreamServer = grpc.BidiStreamingServer[ConsumerCommand, VideoFrame]

func _InventoryService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RequestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RequestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RequestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RequestConnection(ctx, req.(*RequestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ApproveConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ApproveConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ApproveConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ApproveConnection(ctx, req.(*ApproveConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DenyConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DenyConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DenyConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DenyConnection(ctx, req.(*DenyConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_WatchConnectionRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConnectionRequestsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).WatchConnectionRequests(m, &grpc.GenericServerStream[WatchConnectionRequestsRequest, ConnectionRequestNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchConnectionRequestsServer = grpc.ServerStreamingServer[ConnectionRequestNotification]

func _InventoryService_WatchApprovalStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchApprovalStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).WatchApprovalStatus(m, &grpc.GenericServerStream[WatchApprovalStatusRequest, ApprovalStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_WatchApprovalStatusServer = grpc.ServerStreamingServer[ApprovalStatusUpdate]

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _InventoryService_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _InventoryService_ListSessions_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _InventoryService_EndSession_Handler,
		},
		{
			MethodName: "SendWebRTCSignal",
			Handler:    _InventoryService_SendWebRTCSignal_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _InventoryService_Heartbeat_Handler,
		},
		{
			MethodName: "RequestConnection",
			Handler:    _InventoryService_RequestConnection_Handler,
		},
		{
			MethodName: "ApproveConnection",
			Handler:    _InventoryService_ApproveConnection_Handler,
		},
		{
			MethodName: "DenyConnection",
			Handler:    _InventoryService_DenyConnection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWebRTCSignals",
			Handler:       _InventoryService_WatchWebRTCSignals_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProviderStream",
			Handler:       _InventoryService_ProviderStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConsumerStream",
			Handler:       _InventoryService_ConsumerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchConnectionRequests",
			Handler:       _InventoryService_WatchConnectionRequests_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchApprovalStatus",
			Handler:       _InventoryService_WatchApprovalStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventory_service.proto",
}
