// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inventory_service.proto

package remote_inventory

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalStatus int32

const (
	ApprovalStatus_PENDING  ApprovalStatus = 0
	ApprovalStatus_APPROVED ApprovalStatus = 1
	ApprovalStatus_DENIED   ApprovalStatus = 2
)

// Enum value maps for ApprovalStatus.
var (
	ApprovalStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "DENIED",
	}
	ApprovalStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"DENIED":   2,
	}
)

func (x ApprovalStatus) Enum() *ApprovalStatus {
	p := new(ApprovalStatus)
	*p = x
	return p
}

func (x ApprovalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[0].Descriptor()
}

func (ApprovalStatus) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[0]
}

func (x ApprovalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalStatus.Descriptor instead.
func (ApprovalStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{0}
}

type NavigationCommand_Direction int32

const (
	NavigationCommand_UNKNOWN  NavigationCommand_Direction = 0
	NavigationCommand_LEFT     NavigationCommand_Direction = 1
	NavigationCommand_RIGHT    NavigationCommand_Direction = 2
	NavigationCommand_UP       NavigationCommand_Direction = 3
	NavigationCommand_DOWN     NavigationCommand_Direction = 4
	NavigationCommand_FORWARD  NavigationCommand_Direction = 5
	NavigationCommand_BACKWARD NavigationCommand_Direction = 6
)

// Enum value maps for NavigationCommand_Direction.
var (
	NavigationCommand_Direction_name = map[int32]string{
		0: "UNKNOWN",
		1: "LEFT",
		2: "RIGHT",
		3: "UP",
		4: "DOWN",
		5: "FORWARD",
		6: "BACKWARD",
	}
	NavigationCommand_Direction_value = map[string]int32{
		"UNKNOWN":  0,
		"LEFT":     1,
		"RIGHT":    2,
		"UP":       3,
		"DOWN":     4,
		"FORWARD":  5,
		"BACKWARD": 6,
	}
)

func (x NavigationCommand_Direction) Enum() *NavigationCommand_Direction {
	p := new(NavigationCommand_Direction)
	*p = x
	return p
}

func (x NavigationCommand_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationCommand_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[1].Descriptor()
}

func (NavigationCommand_Direction) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[1]
}

func (x NavigationCommand_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationCommand_Direction.Descriptor instead.
func (NavigationCommand_Direction) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{10, 0}
}

type ZoomCommand_ZoomType int32

const (
	ZoomCommand_IN    ZoomCommand_ZoomType = 0
	ZoomCommand_OUT   ZoomCommand_ZoomType = 1
	ZoomCommand_RESET ZoomCommand_ZoomType = 2
)

// Enum value maps for ZoomCommand_ZoomType.
var (
	ZoomCommand_ZoomType_name = map[int32]string{
		0: "IN",
		1: "OUT",
		2: "RESET",
	}
	ZoomCommand_ZoomType_value = map[string]int32{
		"IN":    0,
		"OUT":   1,
		"RESET": 2,
	}
)

func (x ZoomCommand_ZoomType) Enum() *ZoomCommand_ZoomType {
	p := new(ZoomCommand_ZoomType)
	*p = x
	return p
}

func (x ZoomCommand_ZoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoomCommand_ZoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[2].Descriptor()
}

func (ZoomCommand_ZoomType) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[2]
}

func (x ZoomCommand_ZoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoomCommand_ZoomType.Descriptor instead.
func (ZoomCommand_ZoomType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{13, 0}
}

type WebRTCSignal_SignalType int32

const (
	WebRTCSignal_OFFER         WebRTCSignal_SignalType = 0
	WebRTCSignal_ANSWER        WebRTCSignal_SignalType = 1
	WebRTCSignal_ICE_CANDIDATE WebRTCSignal_SignalType = 2
)

// Enum value maps for WebRTCSignal_SignalType.
var (
	WebRTCSignal_SignalType_name = map[int32]string{
		0: "OFFER",
		1: "ANSWER",
		2: "ICE_CANDIDATE",
	}
	WebRTCSignal_SignalType_value = map[string]int32{
		"OFFER":         0,
		"ANSWER":        1,
		"ICE_CANDIDATE": 2,
	}
)

func (x WebRTCSignal_SignalType) Enum() *WebRTCSignal_SignalType {
	p := new(WebRTCSignal_SignalType)
	*p = x
	return p
}

func (x WebRTCSignal_SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebRTCSignal_SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_proto_enumTypes[3].Descriptor()
}

func (WebRTCSignal_SignalType) Type() protoreflect.EnumType {
	return &file_inventory_service_proto_enumTypes[3]
}

func (x WebRTCSignal_SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebRTCSignal_SignalType.Descriptor instead.
func (WebRTCSignal_SignalType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{34, 0}
}

// Session messages
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`     // Provider location/address (deprecated)
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`   // GPS latitude for geocoding
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"` // GPS longitude for geocoding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateSessionRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CreateSessionRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateSessionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateSessionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *JoinSessionRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_inventory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{2}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_inventory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_inventory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Provider messages
type ProviderMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token     string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProviderMessage_VideoFrame
	//	*ProviderMessage_SensorData
	//	*ProviderMessage_Status
	Payload       isProviderMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMessage) Reset() {
	*x = ProviderMessage{}
	mi := &file_inventory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMessage) ProtoMessage() {}

func (x *ProviderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMessage.ProtoReflect.Descriptor instead.
func (*ProviderMessage) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProviderMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProviderMessage) GetPayload() isProviderMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProviderMessage) GetVideoFrame() *VideoFrame {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_VideoFrame); ok {
			return x.VideoFrame
		}
	}
	return nil
}

func (x *ProviderMessage) GetSensorData() *SensorData {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_SensorData); ok {
			return x.SensorData
		}
	}
	return nil
}

func (x *ProviderMessage) GetStatus() *ProviderStatus {
	if x != nil {
		if x, ok := x.Payload.(*ProviderMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isProviderMessage_Payload interface {
	isProviderMessage_Payload()
}

type ProviderMessage_VideoFrame struct {
	VideoFrame *VideoFrame `protobuf:"bytes,3,opt,name=video_frame,json=videoFrame,proto3,oneof"`
}

type ProviderMessage_SensorData struct {
	SensorData *SensorData `protobuf:"bytes,4,opt,name=sensor_data,json=sensorData,proto3,oneof"`
}

type ProviderMessage_Status struct {
	Status *ProviderStatus `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

func (*ProviderMessage_VideoFrame) isProviderMessage_Payload() {}

func (*ProviderMessage_SensorData) isProviderMessage_Payload() {}

func (*ProviderMessage_Status) isProviderMessage_Payload() {}

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameData     []byte                 `protobuf:"bytes,1,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"` // JPEG encoded frame
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	IsBlurred     bool                   `protobuf:"varint,5,opt,name=is_blurred,json=isBlurred,proto3" json:"is_blurred,omitempty"` // Indicates if privacy processing is complete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_inventory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{6}
}

func (x *VideoFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *VideoFrame) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VideoFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFrame) GetIsBlurred() bool {
	if x != nil {
		return x.IsBlurred
	}
	return false
}

type SensorData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccelerometerX float32                `protobuf:"fixed32,1,opt,name=accelerometer_x,json=accelerometerX,proto3" json:"accelerometer_x,omitempty"`
	AccelerometerY float32                `protobuf:"fixed32,2,opt,name=accelerometer_y,json=accelerometerY,proto3" json:"accelerometer_y,omitempty"`
	AccelerometerZ float32                `protobuf:"fixed32,3,opt,name=accelerometer_z,json=accelerometerZ,proto3" json:"accelerometer_z,omitempty"`
	CompassHeading float32                `protobuf:"fixed32,4,opt,name=compass_heading,json=compassHeading,proto3" json:"compass_heading,omitempty"`
	GyroscopeX     float32                `protobuf:"fixed32,5,opt,name=gyroscope_x,json=gyroscopeX,proto3" json:"gyroscope_x,omitempty"`
	GyroscopeY     float32                `protobuf:"fixed32,6,opt,name=gyroscope_y,json=gyroscopeY,proto3" json:"gyroscope_y,omitempty"`
	GyroscopeZ     float32                `protobuf:"fixed32,7,opt,name=gyroscope_z,json=gyroscopeZ,proto3" json:"gyroscope_z,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_inventory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{7}
}

func (x *SensorData) GetAccelerometerX() float32 {
	if x != nil {
		return x.AccelerometerX
	}
	return 0
}

func (x *SensorData) GetAccelerometerY() float32 {
	if x != nil {
		return x.AccelerometerY
	}
	return 0
}

func (x *SensorData) GetAccelerometerZ() float32 {
	if x != nil {
		return x.AccelerometerZ
	}
	return 0
}

func (x *SensorData) GetCompassHeading() float32 {
	if x != nil {
		return x.CompassHeading
	}
	return 0
}

func (x *SensorData) GetGyroscopeX() float32 {
	if x != nil {
		return x.GyroscopeX
	}
	return 0
}

func (x *SensorData) GetGyroscopeY() float32 {
	if x != nil {
		return x.GyroscopeY
	}
	return 0
}

func (x *SensorData) GetGyroscopeZ() float32 {
	if x != nil {
		return x.GyroscopeZ
	}
	return 0
}

type ProviderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraActive  bool                   `protobuf:"varint,1,opt,name=camera_active,json=cameraActive,proto3" json:"camera_active,omitempty"`
	BatteryLevel  int32                  `protobuf:"varint,2,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_inventory_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderStatus) GetCameraActive() bool {
	if x != nil {
		return x.CameraActive
	}
	return false
}

func (x *ProviderStatus) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

// Provider receives commands from Consumer
type ProviderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ProviderCommand_Navigation
	//	*ProviderCommand_Laser
	//	*ProviderCommand_Stop
	//	*ProviderCommand_Zoom
	Command       isProviderCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCommand) Reset() {
	*x = ProviderCommand{}
	mi := &file_inventory_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCommand) ProtoMessage() {}

func (x *ProviderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCommand.ProtoReflect.Descriptor instead.
func (*ProviderCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderCommand) GetCommand() isProviderCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProviderCommand) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *ProviderCommand) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *ProviderCommand) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ProviderCommand) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.Command.(*ProviderCommand_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

type isProviderCommand_Command interface {
	isProviderCommand_Command()
}

type ProviderCommand_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,1,opt,name=navigation,proto3,oneof"`
}

type ProviderCommand_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,2,opt,name=laser,proto3,oneof"`
}

type ProviderCommand_Stop struct {
	Stop *StopCommand `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type ProviderCommand_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,4,opt,name=zoom,proto3,oneof"`
}

func (*ProviderCommand_Navigation) isProviderCommand_Command() {}

func (*ProviderCommand_Laser) isProviderCommand_Command() {}

func (*ProviderCommand_Stop) isProviderCommand_Command() {}

func (*ProviderCommand_Zoom) isProviderCommand_Command() {}

type NavigationCommand struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Direction     NavigationCommand_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=inventory.NavigationCommand_Direction" json:"direction,omitempty"`
	Intensity     float32                     `protobuf:"fixed32,2,opt,name=intensity,proto3" json:"intensity,omitempty"` // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationCommand) Reset() {
	*x = NavigationCommand{}
	mi := &file_inventory_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationCommand) ProtoMessage() {}

func (x *NavigationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationCommand.ProtoReflect.Descriptor instead.
func (*NavigationCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{10}
}

func (x *NavigationCommand) GetDirection() NavigationCommand_Direction {
	if x != nil {
		return x.Direction
	}
	return NavigationCommand_UNKNOWN
}

func (x *NavigationCommand) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type LaserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ScreenX       float32                `protobuf:"fixed32,2,opt,name=screen_x,json=screenX,proto3" json:"screen_x,omitempty"` // Normalized 0.0 to 1.0
	ScreenY       float32                `protobuf:"fixed32,3,opt,name=screen_y,json=screenY,proto3" json:"screen_y,omitempty"` // Normalized 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaserCommand) Reset() {
	*x = LaserCommand{}
	mi := &file_inventory_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaserCommand) ProtoMessage() {}

func (x *LaserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaserCommand.ProtoReflect.Descriptor instead.
func (*LaserCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{11}
}

func (x *LaserCommand) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LaserCommand) GetScreenX() float32 {
	if x != nil {
		return x.ScreenX
	}
	return 0
}

func (x *LaserCommand) GetScreenY() float32 {
	if x != nil {
		return x.ScreenY
	}
	return 0
}

type StopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emergency     bool                   `protobuf:"varint,1,opt,name=emergency,proto3" json:"emergency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCommand) Reset() {
	*x = StopCommand{}
	mi := &file_inventory_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCommand) ProtoMessage() {}

func (x *StopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCommand.ProtoReflect.Descriptor instead.
func (*StopCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{12}
}

func (x *StopCommand) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

type ZoomCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ZoomCommand_ZoomType   `protobuf:"varint,1,opt,name=type,proto3,enum=inventory.ZoomCommand_ZoomType" json:"type,omitempty"`
	Level         float32                `protobuf:"fixed32,2,opt,name=level,proto3" json:"level,omitempty"` // Current zoom level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoomCommand) Reset() {
	*x = ZoomCommand{}
	mi := &file_inventory_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoomCommand) ProtoMessage() {}

func (x *ZoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoomCommand.ProtoReflect.Descriptor instead.
func (*ZoomCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{13}
}

func (x *ZoomCommand) GetType() ZoomCommand_ZoomType {
	if x != nil {
		return x.Type
	}
	return ZoomCommand_IN
}

func (x *ZoomCommand) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Consumer messages
type ConsumerCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token     string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ConsumerCommand_Navigation
	//	*ConsumerCommand_Laser
	//	*ConsumerCommand_Stop
	//	*ConsumerCommand_Zoom
	//	*ConsumerCommand_Voice
	//	*ConsumerCommand_Text
	Command       isConsumerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerCommand) Reset() {
	*x = ConsumerCommand{}
	mi := &file_inventory_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerCommand) ProtoMessage() {}

func (x *ConsumerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerCommand.ProtoReflect.Descriptor instead.
func (*ConsumerCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{14}
}

func (x *ConsumerCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsumerCommand) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsumerCommand) GetCommand() isConsumerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ConsumerCommand) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *ConsumerCommand) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *ConsumerCommand) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ConsumerCommand) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

func (x *ConsumerCommand) GetVoice() *VoiceCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *ConsumerCommand) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.Command.(*ConsumerCommand_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isConsumerCommand_Command interface {
	isConsumerCommand_Command()
}

type ConsumerCommand_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,3,opt,name=navigation,proto3,oneof"`
}

type ConsumerCommand_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,4,opt,name=laser,proto3,oneof"`
}

type ConsumerCommand_Stop struct {
	Stop *StopCommand `protobuf:"bytes,5,opt,name=stop,proto3,oneof"`
}

type ConsumerCommand_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,6,opt,name=zoom,proto3,oneof"`
}

type ConsumerCommand_Voice struct {
	Voice *VoiceCommand `protobuf:"bytes,7,opt,name=voice,proto3,oneof"`
}

type ConsumerCommand_Text struct {
	Text *TextCommand `protobuf:"bytes,8,opt,name=text,proto3,oneof"`
}

func (*ConsumerCommand_Navigation) isConsumerCommand_Command() {}

func (*ConsumerCommand_Laser) isConsumerCommand_Command() {}

func (*ConsumerCommand_Stop) isConsumerCommand_Command() {}

func (*ConsumerCommand_Zoom) isConsumerCommand_Command() {}

func (*ConsumerCommand_Voice) isConsumerCommand_Command() {}

func (*ConsumerCommand_Text) isConsumerCommand_Command() {}

type VoiceCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TranscribedText string                 `protobuf:"bytes,1,opt,name=transcribed_text,json=transcribedText,proto3" json:"transcribed_text,omitempty"`
	Confidence      float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoiceCommand) Reset() {
	*x = VoiceCommand{}
	mi := &file_inventory_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCommand) ProtoMessage() {}

func (x *VoiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCommand.ProtoReflect.Descriptor instead.
func (*VoiceCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{15}
}

func (x *VoiceCommand) GetTranscribedText() string {
	if x != nil {
		return x.TranscribedText
	}
	return ""
}

func (x *VoiceCommand) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type TextCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCommand) Reset() {
	*x = TextCommand{}
	mi := &file_inventory_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCommand) ProtoMessage() {}

func (x *TextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCommand.ProtoReflect.Descriptor instead.
func (*TextCommand) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{16}
}

func (x *TextCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "provider" or "consumer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_inventory_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_inventory_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConnectionRequest) Reset() {
	*x = RequestConnectionRequest{}
	mi := &file_inventory_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConnectionRequest) ProtoMessage() {}

func (x *RequestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConnectionRequest.ProtoReflect.Descriptor instead.
func (*RequestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{19}
}

func (x *RequestConnectionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestConnectionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *RequestConnectionRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type RequestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConnectionResponse) Reset() {
	*x = RequestConnectionResponse{}
	mi := &file_inventory_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConnectionResponse) ProtoMessage() {}

func (x *RequestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConnectionResponse.ProtoReflect.Descriptor instead.
func (*RequestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{20}
}

func (x *RequestConnectionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveConnectionRequest) Reset() {
	*x = ApproveConnectionRequest{}
	mi := &file_inventory_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveConnectionRequest) ProtoMessage() {}

func (x *ApproveConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveConnectionRequest.ProtoReflect.Descriptor instead.
func (*ApproveConnectionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{21}
}

func (x *ApproveConnectionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // WebRTC signaling token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveConnectionResponse) Reset() {
	*x = ApproveConnectionResponse{}
	mi := &file_inventory_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveConnectionResponse) ProtoMessage() {}

func (x *ApproveConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveConnectionResponse.ProtoReflect.Descriptor instead.
func (*ApproveConnectionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{22}
}

func (x *ApproveConnectionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApproveConnectionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DenyConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyConnectionRequest) Reset() {
	*x = DenyConnectionRequest{}
	mi := &file_inventory_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyConnectionRequest) ProtoMessage() {}

func (x *DenyConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyConnectionRequest.ProtoReflect.Descriptor instead.
func (*DenyConnectionRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{23}
}

func (x *DenyConnectionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyConnectionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyConnectionResponse) Reset() {
	*x = DenyConnectionResponse{}
	mi := &file_inventory_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyConnectionResponse) ProtoMessage() {}

func (x *DenyConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyConnectionResponse.ProtoReflect.Descriptor instead.
func (*DenyConnectionResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{24}
}

func (x *DenyConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchConnectionRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConnectionRequestsRequest) Reset() {
	*x = WatchConnectionRequestsRequest{}
	mi := &file_inventory_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConnectionRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConnectionRequestsRequest) ProtoMessage() {}

func (x *WatchConnectionRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConnectionRequestsRequest.ProtoReflect.Descriptor instead.
func (*WatchConnectionRequestsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{25}
}

func (x *WatchConnectionRequestsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConnectionRequestNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequestNotification) Reset() {
	*x = ConnectionRequestNotification{}
	mi := &file_inventory_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequestNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequestNotification) ProtoMessage() {}

func (x *ConnectionRequestNotification) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequestNotification.ProtoReflect.Descriptor instead.
func (*ConnectionRequestNotification) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{26}
}

func (x *ConnectionRequestNotification) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectionRequestNotification) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConnectionRequestNotification) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ConnectionRequestNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WatchApprovalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchApprovalStatusRequest) Reset() {
	*x = WatchApprovalStatusRequest{}
	mi := &file_inventory_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchApprovalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchApprovalStatusRequest) ProtoMessage() {}

func (x *WatchApprovalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchApprovalStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchApprovalStatusRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{27}
}

func (x *WatchApprovalStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApprovalStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ApprovalStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=inventory.ApprovalStatus" json:"status,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStatusUpdate) Reset() {
	*x = ApprovalStatusUpdate{}
	mi := &file_inventory_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStatusUpdate) ProtoMessage() {}

func (x *ApprovalStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStatusUpdate.ProtoReflect.Descriptor instead.
func (*ApprovalStatusUpdate) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{28}
}

func (x *ApprovalStatusUpdate) GetStatus() ApprovalStatus {
	if x != nil {
		return x.Status
	}
	return ApprovalStatus_PENDING
}

func (x *ApprovalStatusUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApprovalStatusUpdate) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApprovalStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Session Discovery Messages
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_inventory_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListSessionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_inventory_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{30}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProviderName         string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Location             string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`                                         // Deprecated, use formatted_address
	FormattedAddress     string                 `protobuf:"bytes,4,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"` // Geocoded address (e.g., "San Francisco, CA")
	Latitude             float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`                                       // GPS latitude
	Longitude            float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`                                     // GPS longitude
	InActiveCall         bool                   `protobuf:"varint,7,opt,name=in_active_call,json=inActiveCall,proto3" json:"in_active_call,omitempty"`          // True if provider is currently in a call
	CreatedAt            int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AcceptingConnections bool                   `protobuf:"varint,9,opt,name=accepting_connections,json=acceptingConnections,proto3" json:"accepting_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_inventory_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{31}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SessionInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SessionInfo) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *SessionInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SessionInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SessionInfo) GetInActiveCall() bool {
	if x != nil {
		return x.InActiveCall
	}
	return false
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetAcceptingConnections() bool {
	if x != nil {
		return x.AcceptingConnections
	}
	return false
}

// Command Messages
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to CommandType:
	//
	//	*Command_Navigation
	//	*Command_Laser
	//	*Command_Stop
	//	*Command_Zoom
	//	*Command_Voice
	//	*Command_Text
	CommandType   isCommand_CommandType `protobuf_oneof:"command_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_inventory_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{32}
}

func (x *Command) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Command) GetCommandType() isCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return nil
}

func (x *Command) GetNavigation() *NavigationCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Navigation); ok {
			return x.Navigation
		}
	}
	return nil
}

func (x *Command) GetLaser() *LaserCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Laser); ok {
			return x.Laser
		}
	}
	return nil
}

func (x *Command) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetZoom() *ZoomCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Zoom); ok {
			return x.Zoom
		}
	}
	return nil
}

func (x *Command) GetVoice() *VoiceCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *Command) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.CommandType.(*Command_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isCommand_CommandType interface {
	isCommand_CommandType()
}

type Command_Navigation struct {
	Navigation *NavigationCommand `protobuf:"bytes,2,opt,name=navigation,proto3,oneof"`
}

type Command_Laser struct {
	Laser *LaserCommand `protobuf:"bytes,3,opt,name=laser,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopCommand `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type Command_Zoom struct {
	Zoom *ZoomCommand `protobuf:"bytes,5,opt,name=zoom,proto3,oneof"`
}

type Command_Voice struct {
	Voice *VoiceCommand `protobuf:"bytes,6,opt,name=voice,proto3,oneof"`
}

type Command_Text struct {
	Text *TextCommand `protobuf:"bytes,7,opt,name=text,proto3,oneof"`
}

func (*Command_Navigation) isCommand_CommandType() {}

func (*Command_Laser) isCommand_CommandType() {}

func (*Command_Stop) isCommand_CommandType() {}

func (*Command_Zoom) isCommand_CommandType() {}

func (*Command_Voice) isCommand_CommandType() {}

func (*Command_Text) isCommand_CommandType() {}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_inventory_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{33}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WebRTCSignal struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionId     string                  `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromDeviceId  string                  `protobuf:"bytes,2,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"`
	ToDeviceId    string                  `protobuf:"bytes,3,opt,name=to_device_id,json=toDeviceId,proto3" json:"to_device_id,omitempty"`
	Type          WebRTCSignal_SignalType `protobuf:"varint,4,opt,name=type,proto3,enum=inventory.WebRTCSignal_SignalType" json:"type,omitempty"`
	Payload       string                  `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded SDP or ICE candidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCSignal) Reset() {
	*x = WebRTCSignal{}
	mi := &file_inventory_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCSignal) ProtoMessage() {}

func (x *WebRTCSignal) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCSignal.ProtoReflect.Descriptor instead.
func (*WebRTCSignal) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{34}
}

func (x *WebRTCSignal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WebRTCSignal) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *WebRTCSignal) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *WebRTCSignal) GetType() WebRTCSignal_SignalType {
	if x != nil {
		return x.Type
	}
	return WebRTCSignal_OFFER
}

func (x *WebRTCSignal) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_inventory_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{35}
}

func (x *SignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // Device watching for signals
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSignalsRequest) Reset() {
	*x = WatchSignalsRequest{}
	mi := &file_inventory_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSignalsRequest) ProtoMessage() {}

func (x *WatchSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSignalsRequest.ProtoReflect.Descriptor instead.
func (*WatchSignalsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{36}
}

func (x *WatchSignalsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchSignalsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_inventory_service_proto protoreflect.FileDescriptor

const file_inventory_service_proto_rawDesc = "" +
	"\n" +
	"\x17inventory_service.proto\x12\tinventory\x1a\x1cgoogle/api/annotations.proto\"\xb2\x01\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"y\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\"z\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"H\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\".\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xfa\x01\n" +
	"\x0fProviderMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x128\n" +
	"\vvideo_frame\x18\x03 \x01(\v2\x15.inventory.VideoFrameH\x00R\n" +
	"videoFrame\x128\n" +
	"\vsensor_data\x18\x04 \x01(\v2\x15.inventory.SensorDataH\x00R\n" +
	"sensorData\x123\n" +
	"\x06status\x18\x05 \x01(\v2\x19.inventory.ProviderStatusH\x00R\x06statusB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\n" +
	"VideoFrame\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x01 \x01(\fR\tframeData\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"is_blurred\x18\x05 \x01(\bR\tisBlurred\"\x93\x02\n" +
	"\n" +
	"SensorData\x12'\n" +
	"\x0faccelerometer_x\x18\x01 \x01(\x02R\x0eaccelerometerX\x12'\n" +
	"\x0faccelerometer_y\x18\x02 \x01(\x02R\x0eaccelerometerY\x12'\n" +
	"\x0faccelerometer_z\x18\x03 \x01(\x02R\x0eaccelerometerZ\x12'\n" +
	"\x0fcompass_heading\x18\x04 \x01(\x02R\x0ecompassHeading\x12\x1f\n" +
	"\vgyroscope_x\x18\x05 \x01(\x02R\n" +
	"gyroscopeX\x12\x1f\n" +
	"\vgyroscope_y\x18\x06 \x01(\x02R\n" +
	"gyroscopeY\x12\x1f\n" +
	"\vgyroscope_z\x18\a \x01(\x02R\n" +
	"gyroscopeZ\"Z\n" +
	"\x0eProviderStatus\x12#\n" +
	"\rcamera_active\x18\x01 \x01(\bR\fcameraActive\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x05R\fbatteryLevel\"\xe9\x01\n" +
	"\x0fProviderCommand\x12>\n" +
	"\n" +
	"navigation\x18\x01 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x02 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x03 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x04 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoomB\t\n" +
	"\acommand\"\xd3\x01\n" +
	"\x11NavigationCommand\x12D\n" +
	"\tdirection\x18\x01 \x01(\x0e2&.inventory.NavigationCommand.DirectionR\tdirection\x12\x1c\n" +
	"\tintensity\x18\x02 \x01(\x02R\tintensity\"Z\n" +
	"\tDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\x06\n" +
	"\x02UP\x10\x03\x12\b\n" +
	"\x04DOWN\x10\x04\x12\v\n" +
	"\aFORWARD\x10\x05\x12\f\n" +
	"\bBACKWARD\x10\x06\"\\\n" +
	"\fLaserCommand\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x19\n" +
	"\bscreen_x\x18\x02 \x01(\x02R\ascreenX\x12\x19\n" +
	"\bscreen_y\x18\x03 \x01(\x02R\ascreenY\"+\n" +
	"\vStopCommand\x12\x1c\n" +
	"\temergency\x18\x01 \x01(\bR\temergency\"\x80\x01\n" +
	"\vZoomCommand\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.inventory.ZoomCommand.ZoomTypeR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x02R\x05level\"&\n" +
	"\bZoomType\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03OUT\x10\x01\x12\t\n" +
	"\x05RESET\x10\x02\"\xfd\x02\n" +
	"\x0fConsumerCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12>\n" +
	"\n" +
	"navigation\x18\x03 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x04 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x05 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x06 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoom\x12/\n" +
	"\x05voice\x18\a \x01(\v2\x17.inventory.VoiceCommandH\x00R\x05voice\x12,\n" +
	"\x04text\x18\b \x01(\v2\x16.inventory.TextCommandH\x00R\x04textB\t\n" +
	"\acommand\"Y\n" +
	"\fVoiceCommand\x12)\n" +
	"\x10transcribed_text\x18\x01 \x01(\tR\x0ftranscribedText\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"!\n" +
	"\vTextCommand\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"[\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x18RequestConnectionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\":\n" +
	"\x19RequestConnectionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"9\n" +
	"\x18ApproveConnectionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"P\n" +
	"\x19ApproveConnectionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"N\n" +
	"\x15DenyConnectionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"2\n" +
	"\x16DenyConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x1eWatchConnectionRequestsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa2\x01\n" +
	"\x1dConnectionRequestNotification\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\";\n" +
	"\x1aWatchApprovalStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x98\x01\n" +
	"\x14ApprovalStatusUpdate\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.inventory.ApprovalStatusR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"8\n" +
	"\x13ListSessionsRequest\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\"J\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.inventory.SessionInfoR\bsessions\"\xce\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12+\n" +
	"\x11formatted_address\x18\x04 \x01(\tR\x10formattedAddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12$\n" +
	"\x0ein_active_call\x18\a \x01(\bR\finActiveCall\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x123\n" +
	"\x15accepting_connections\x18\t \x01(\bR\x14acceptingConnections\"\xe4\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\n" +
	"navigation\x18\x02 \x01(\v2\x1c.inventory.NavigationCommandH\x00R\n" +
	"navigation\x12/\n" +
	"\x05laser\x18\x03 \x01(\v2\x17.inventory.LaserCommandH\x00R\x05laser\x12,\n" +
	"\x04stop\x18\x04 \x01(\v2\x16.inventory.StopCommandH\x00R\x04stop\x12,\n" +
	"\x04zoom\x18\x05 \x01(\v2\x16.inventory.ZoomCommandH\x00R\x04zoom\x12/\n" +
	"\x05voice\x18\x06 \x01(\v2\x17.inventory.VoiceCommandH\x00R\x05voice\x12,\n" +
	"\x04text\x18\a \x01(\v2\x16.inventory.TextCommandH\x00R\x04textB\x0e\n" +
	"\fcommand_type\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xff\x01\n" +
	"\fWebRTCSignal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12$\n" +
	"\x0efrom_device_id\x18\x02 \x01(\tR\ffromDeviceId\x12 \n" +
	"\fto_device_id\x18\x03 \x01(\tR\n" +
	"toDeviceId\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".inventory.WebRTCSignal.SignalTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\"6\n" +
	"\n" +
	"SignalType\x12\t\n" +
	"\x05OFFER\x10\x00\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x01\x12\x11\n" +
	"\rICE_CANDIDATE\x10\x02\"D\n" +
	"\x0eSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x13WatchSignalsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId*7\n" +
	"\x0eApprovalStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\n" +
	"\n" +
	"\x06DENIED\x10\x022\xe8\v\n" +
	"\x10InventoryService\x12e\n" +
	"\rCreateSession\x12\x1f.inventory.CreateSessionRequest\x1a\x1a.inventory.SessionResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12e\n" +
	"\fListSessions\x12\x1e.inventory.ListSessionsRequest\x1a\x1f.inventory.ListSessionsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/sessions\x12l\n" +
	"\n" +
	"EndSession\x12\x1c.inventory.EndSessionRequest\x1a\x1d.inventory.EndSessionResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/sessions/{session_id}\x12d\n" +
	"\x10SendWebRTCSignal\x12\x17.inventory.WebRTCSignal\x1a\x19.inventory.SignalResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/webrtc/signal\x12Q\n" +
	"\x12WatchWebRTCSignals\x12\x1e.inventory.WatchSignalsRequest\x1a\x17.inventory.WebRTCSignal\"\x000\x01\x12L\n" +
	"\x0eProviderStream\x12\x1a.inventory.ProviderMessage\x1a\x1a.inventory.ProviderCommand(\x010\x01\x12G\n" +
	"\x0eConsumerStream\x12\x1a.inventory.ConsumerCommand\x1a\x15.inventory.VideoFrame(\x010\x01\x12v\n" +
	"\tHeartbeat\x12\x1b.inventory.HeartbeatRequest\x1a\x1c.inventory.HeartbeatResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/sessions/{session_id}/heartbeat\x12\x8c\x01\n" +
	"\x11RequestConnection\x12#.inventory.RequestConnectionRequest\x1a$.inventory.RequestConnectionResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/sessions/{session_id}/connect\x12\x8c\x01\n" +
	"\x11ApproveConnection\x12#.inventory.ApproveConnectionRequest\x1a$.inventory.ApproveConnectionResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/requests/{request_id}/approve\x12\x80\x01\n" +
	"\x0eDenyConnection\x12 .inventory.DenyConnectionRequest\x1a!.inventory.DenyConnectionResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/requests/{request_id}/deny\x12\xa2\x01\n" +
	"\x17WatchConnectionRequests\x12).inventory.WatchConnectionRequestsRequest\x1a(.inventory.ConnectionRequestNotification\"0\x82\xd3\xe4\x93\x02*\x12(/v1/sessions/{session_id}/requests/watch0\x01\x12\x89\x01\n" +
	"\x13WatchApprovalStatus\x12%.inventory.WatchApprovalStatusRequest\x1a\x1f.inventory.ApprovalStatusUpdate\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/requests/{request_id}/status0\x01B$Z\"github.com/djgupt/remote-inventoryb\x06proto3"

var (
	file_inventory_service_proto_rawDescOnce sync.Once
	file_inventory_service_proto_rawDescData []byte
)

func file_inventory_service_proto_rawDescGZIP() []byte {
	file_inventory_service_proto_rawDescOnce.Do(func() {
		file_inventory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)))
	})
	return file_inventory_service_proto_rawDescData
}

var file_inventory_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_inventory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_inventory_service_proto_goTypes = []any{
	(ApprovalStatus)(0),                    // 0: inventory.ApprovalStatus
	(NavigationCommand_Direction)(0),       // 1: inventory.NavigationCommand.Direction
	(ZoomCommand_ZoomType)(0),              // 2: inventory.ZoomCommand.ZoomType
	(WebRTCSignal_SignalType)(0),           // 3: inventory.WebRTCSignal.SignalType
	(*CreateSessionRequest)(nil),           // 4: inventory.CreateSessionRequest
	(*JoinSessionRequest)(nil),             // 5: inventory.JoinSessionRequest
	(*SessionResponse)(nil),                // 6: inventory.SessionResponse
	(*EndSessionRequest)(nil),              // 7: inventory.EndSessionRequest
	(*EndSessionResponse)(nil),             // 8: inventory.EndSessionResponse
	(*ProviderMessage)(nil),                // 9: inventory.ProviderMessage
	(*VideoFrame)(nil),                     // 10: inventory.VideoFrame
	(*SensorData)(nil),                     // 11: inventory.SensorData
	(*ProviderStatus)(nil),                 // 12: inventory.ProviderStatus
	(*ProviderCommand)(nil),                // 13: inventory.ProviderCommand
	(*NavigationCommand)(nil),              // 14: inventory.NavigationCommand
	(*LaserCommand)(nil),                   // 15: inventory.LaserCommand
	(*StopCommand)(nil),                    // 16: inventory.StopCommand
	(*ZoomCommand)(nil),                    // 17: inventory.ZoomCommand
	(*ConsumerCommand)(nil),                // 18: inventory.ConsumerCommand
	(*VoiceCommand)(nil),                   // 19: inventory.VoiceCommand
	(*TextCommand)(nil),                    // 20: inventory.TextCommand
	(*HeartbeatRequest)(nil),               // 21: inventory.HeartbeatRequest
	(*HeartbeatResponse)(nil),              // 22: inventory.HeartbeatResponse
	(*RequestConnectionRequest)(nil),       // 23: inventory.RequestConnectionRequest
	(*RequestConnectionResponse)(nil),      // 24: inventory.RequestConnectionResponse
	(*ApproveConnectionRequest)(nil),       // 25: inventory.ApproveConnectionRequest
	(*ApproveConnectionResponse)(nil),      // 26: inventory.ApproveConnectionResponse
	(*DenyConnectionRequest)(nil),          // 27: inventory.DenyConnectionRequest
	(*DenyConnectionResponse)(nil),         // 28: inventory.DenyConnectionResponse
	(*WatchConnectionRequestsRequest)(nil), // 29: inventory.WatchConnectionRequestsRequest
	(*ConnectionRequestNotification)(nil),  // 30: inventory.ConnectionRequestNotification
	(*WatchApprovalStatusRequest)(nil),     // 31: inventory.WatchApprovalStatusRequest
	(*ApprovalStatusUpdate)(nil),           // 32: inventory.ApprovalStatusUpdate
	(*ListSessionsRequest)(nil),            // 33: inventory.ListSessionsRequest
	(*ListSessionsResponse)(nil),           // 34: inventory.ListSessionsResponse
	(*SessionInfo)(nil),                    // 35: inventory.SessionInfo
	(*Command)(nil),                        // 36: inventory.Command
	(*CommandResponse)(nil),                // 37: inventory.CommandResponse
	(*WebRTCSignal)(nil),                   // 38: inventory.WebRTCSignal
	(*SignalResponse)(nil),                 // 39: inventory.SignalResponse
	(*WatchSignalsRequest)(nil),            // 40: inventory.WatchSignalsRequest
}
var file_inventory_service_proto_depIdxs = []int32{
	10, // 0: inventory.ProviderMessage.video_frame:type_name -> inventory.VideoFrame
	11, // 1: inventory.ProviderMessage.sensor_data:type_name -> inventory.SensorData
	12, // 2: inventory.ProviderMessage.status:type_name -> inventory.ProviderStatus
	14, // 3: inventory.ProviderCommand.navigation:type_name -> inventory.NavigationCommand
	15, // 4: inventory.ProviderCommand.laser:type_name -> inventory.LaserCommand
	16, // 5: inventory.ProviderCommand.stop:type_name -> inventory.StopCommand
	17, // 6: inventory.ProviderCommand.zoom:type_name -> inventory.ZoomCommand
	1,  // 7: inventory.NavigationCommand.direction:type_name -> inventory.NavigationCommand.Direction
	2,  // 8: inventory.ZoomCommand.type:type_name -> inventory.ZoomCommand.ZoomType
	14, // 9: inventory.ConsumerCommand.navigation:type_name -> inventory.NavigationCommand
	15, // 10: inventory.ConsumerCommand.laser:type_name -> inventory.LaserCommand
	16, // 11: inventory.ConsumerCommand.stop:type_name -> inventory.StopCommand
	17, // 12: inventory.ConsumerCommand.zoom:type_name -> inventory.ZoomCommand
	19, // 13: inventory.ConsumerCommand.voice:type_name -> inventory.VoiceCommand
	20, // 14: inventory.ConsumerCommand.text:type_name -> inventory.TextCommand
	0,  // 15: inventory.ApprovalStatusUpdate.status:type_name -> inventory.ApprovalStatus
	35, // 16: inventory.ListSessionsResponse.sessions:type_name -> inventory.SessionInfo
	14, // 17: inventory.Command.navigation:type_name -> inventory.NavigationCommand
	15, // 18: inventory.Command.laser:type_name -> inventory.LaserCommand
	16, // 19: inventory.Command.stop:type_name -> inventory.StopCommand
	17, // 20: inventory.Command.zoom:type_name -> inventory.ZoomCommand
	19, // 21: inventory.Command.voice:type_name -> inventory.VoiceCommand
	20, // 22: inventory.Command.text:type_name -> inventory.TextCommand
	3,  // 23: inventory.WebRTCSignal.type:type_name -> inventory.WebRTCSignal.SignalType
	4,  // 24: inventory.InventoryService.CreateSession:input_type -> inventory.CreateSessionRequest
	33, // 25: inventory.InventoryService.ListSessions:input_type -> inventory.ListSessionsRequest
	7,  // 26: inventory.InventoryService.EndSession:input_type -> inventory.EndSessionRequest
	38, // 27: inventory.InventoryService.SendWebRTCSignal:input_type -> inventory.WebRTCSignal
	40, // 28: inventory.InventoryService.WatchWebRTCSignals:input_type -> inventory.WatchSignalsRequest
	9,  // 29: inventory.InventoryService.ProviderStream:input_type -> inventory.ProviderMessage
	18, // 30: inventory.InventoryService.ConsumerStream:input_type -> inventory.ConsumerCommand
	21, // 31: inventory.InventoryService.Heartbeat:input_type -> inventory.HeartbeatRequest
	23, // 32: inventory.InventoryService.RequestConnection:input_type -> inventory.RequestConnectionRequest
	25, // 33: inventory.InventoryService.ApproveConnection:input_type -> inventory.ApproveConnectionRequest
	27, // 34: inventory.InventoryService.DenyConnection:input_type -> inventory.DenyConnectionRequest
	29, // 35: inventory.InventoryService.WatchConnectionRequests:input_type -> inventory.WatchConnectionRequestsRequest
	31, // 36: inventory.InventoryService.WatchApprovalStatus:input_type -> inventory.WatchApprovalStatusRequest
	6,  // 37: inventory.InventoryService.CreateSession:output_type -> inventory.SessionResponse
	34, // 38: inventory.InventoryService.ListSessions:output_type -> inventory.ListSessionsResponse
	8,  // 39: inventory.InventoryService.EndSession:output_type -> inventory.EndSessionResponse
	39, // 40: inventory.InventoryService.SendWebRTCSignal:output_type -> inventory.SignalResponse
	38, // 41: inventory.InventoryService.WatchWebRTCSignals:output_type -> inventory.WebRTCSignal
	13, // 42: inventory.InventoryService.ProviderStream:output_type -> inventory.ProviderCommand
	10, // 43: inventory.InventoryService.ConsumerStream:output_type -> inventory.VideoFrame
	22, // 44: inventory.InventoryService.Heartbeat:output_type -> inventory.HeartbeatResponse
	24, // 45: inventory.InventoryService.RequestConnection:output_type -> inventory.RequestConnectionResponse
	26, // 46: inventory.InventoryService.ApproveConnection:output_type -> inventory.ApproveConnectionResponse
	28, // 47: inventory.InventoryService.DenyConnection:output_type -> inventory.DenyConnectionResponse
	30, // 48: inventory.InventoryService.WatchConnectionRequests:output_type -> inventory.ConnectionRequestNotification
	32, // 49: inventory.InventoryService.WatchApprovalStatus:output_type -> inventory.ApprovalStatusUpdate
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_inventory_service_proto_init() }
func file_inventory_service_proto_init() {
	if File_inventory_service_proto != nil {
		return
	}
	file_inventory_service_proto_msgTypes[5].OneofWrappers = []any{
		(*ProviderMessage_VideoFrame)(nil),
		(*ProviderMessage_SensorData)(nil),
		(*ProviderMessage_Status)(nil),
	}
	file_inventory_service_proto_msgTypes[9].OneofWrappers = []any{
		(*ProviderCommand_Navigation)(nil),
		(*ProviderCommand_Laser)(nil),
		(*ProviderCommand_Stop)(nil),
		(*ProviderCommand_Zoom)(nil),
	}
	file_inventory_service_proto_msgTypes[14].OneofWrappers = []any{
		(*ConsumerCommand_Navigation)(nil),
		(*ConsumerCommand_Laser)(nil),
		(*ConsumerCommand_Stop)(nil),
		(*ConsumerCommand_Zoom)(nil),
		(*ConsumerCommand_Voice)(nil),
		(*ConsumerCommand_Text)(nil),
	}
	file_inventory_service_proto_msgTypes[32].OneofWrappers = []any{
		(*Command_Navigation)(nil),
		(*Command_Laser)(nil),
		(*Command_Stop)(nil),
		(*Command_Zoom)(nil),
		(*Command_Voice)(nil),
		(*Command_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_proto_goTypes,
		DependencyIndexes: file_inventory_service_proto_depIdxs,
		EnumInfos:         file_inventory_service_proto_enumTypes,
		MessageInfos:      file_inventory_service_proto_msgTypes,
	}.Build()
	File_inventory_service_proto = out.File
	file_inventory_service_proto_goTypes = nil
	file_inventory_service_proto_depIdxs = nil
}
