# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_service_pb2 as inventory__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteInventoryServiceStub(object):
    """Session management and video streaming service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/inventory.RemoteInventoryService/CreateSession',
                request_serializer=inventory__service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/inventory.RemoteInventoryService/ListSessions',
                request_serializer=inventory__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.RequestConnection = channel.unary_unary(
                '/inventory.RemoteInventoryService/RequestConnection',
                request_serializer=inventory__service__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ConnectionResponse.FromString,
                _registered_method=True)
        self.WatchConnectionRequests = channel.unary_stream(
                '/inventory.RemoteInventoryService/WatchConnectionRequests',
                request_serializer=inventory__service__pb2.WatchRequestsRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ConnectionRequestNotification.FromString,
                _registered_method=True)
        self.ApproveConnection = channel.unary_unary(
                '/inventory.RemoteInventoryService/ApproveConnection',
                request_serializer=inventory__service__pb2.ApproveRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ApproveResponse.FromString,
                _registered_method=True)
        self.DenyConnection = channel.unary_unary(
                '/inventory.RemoteInventoryService/DenyConnection',
                request_serializer=inventory__service__pb2.DenyRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.DenyResponse.FromString,
                _registered_method=True)
        self.WatchApprovalStatus = channel.unary_stream(
                '/inventory.RemoteInventoryService/WatchApprovalStatus',
                request_serializer=inventory__service__pb2.WatchApprovalRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ApprovalStatusUpdate.FromString,
                _registered_method=True)
        self.SendWebRTCSignal = channel.unary_unary(
                '/inventory.RemoteInventoryService/SendWebRTCSignal',
                request_serializer=inventory__service__pb2.WebRTCSignal.SerializeToString,
                response_deserializer=inventory__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.WatchWebRTCSignals = channel.unary_stream(
                '/inventory.RemoteInventoryService/WatchWebRTCSignals',
                request_serializer=inventory__service__pb2.WatchSignalsRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.WebRTCSignal.FromString,
                _registered_method=True)
        self.StreamVideo = channel.stream_stream(
                '/inventory.RemoteInventoryService/StreamVideo',
                request_serializer=inventory__service__pb2.VideoFrame.SerializeToString,
                response_deserializer=inventory__service__pb2.VideoFrame.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/inventory.RemoteInventoryService/SendCommand',
                request_serializer=inventory__service__pb2.Command.SerializeToString,
                response_deserializer=inventory__service__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/inventory.RemoteInventoryService/EndSession',
                request_serializer=inventory__service__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.ProviderStream = channel.stream_stream(
                '/inventory.RemoteInventoryService/ProviderStream',
                request_serializer=inventory__service__pb2.ProviderMessage.SerializeToString,
                response_deserializer=inventory__service__pb2.ProviderCommand.FromString,
                _registered_method=True)
        self.ConsumerStream = channel.stream_stream(
                '/inventory.RemoteInventoryService/ConsumerStream',
                request_serializer=inventory__service__pb2.ConsumerCommand.SerializeToString,
                response_deserializer=inventory__service__pb2.VideoFrame.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/inventory.RemoteInventoryService/Heartbeat',
                request_serializer=inventory__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class RemoteInventoryServiceServicer(object):
    """Session management and video streaming service
    """

    def CreateSession(self, request, context):
        """Create a new session for a provider
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List all active sessions (for consumers to discover providers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestConnection(self, request, context):
        """Consumer requests to connect to a provider session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchConnectionRequests(self, request, context):
        """Provider watches for incoming connection requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveConnection(self, request, context):
        """Provider approves a connection request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenyConnection(self, request, context):
        """Provider denies a connection request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchApprovalStatus(self, request, context):
        """Consumer watches for approval status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWebRTCSignal(self, request, context):
        """WebRTC Signaling (NEW)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchWebRTCSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVideo(self, request_iterator, context):
        """Streaming video (existing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Send command to provider (existing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProviderStream(self, request_iterator, context):
        """Bidirectional streaming for Provider video upload and command reception
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumerStream(self, request_iterator, context):
        """Consumer receives privacy-blurred video and sends commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat to keep sessions alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteInventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=inventory__service__pb2.CreateSessionRequest.FromString,
                    response_serializer=inventory__service__pb2.SessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=inventory__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=inventory__service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'RequestConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestConnection,
                    request_deserializer=inventory__service__pb2.ConnectionRequest.FromString,
                    response_serializer=inventory__service__pb2.ConnectionResponse.SerializeToString,
            ),
            'WatchConnectionRequests': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchConnectionRequests,
                    request_deserializer=inventory__service__pb2.WatchRequestsRequest.FromString,
                    response_serializer=inventory__service__pb2.ConnectionRequestNotification.SerializeToString,
            ),
            'ApproveConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveConnection,
                    request_deserializer=inventory__service__pb2.ApproveRequest.FromString,
                    response_serializer=inventory__service__pb2.ApproveResponse.SerializeToString,
            ),
            'DenyConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.DenyConnection,
                    request_deserializer=inventory__service__pb2.DenyRequest.FromString,
                    response_serializer=inventory__service__pb2.DenyResponse.SerializeToString,
            ),
            'WatchApprovalStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchApprovalStatus,
                    request_deserializer=inventory__service__pb2.WatchApprovalRequest.FromString,
                    response_serializer=inventory__service__pb2.ApprovalStatusUpdate.SerializeToString,
            ),
            'SendWebRTCSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWebRTCSignal,
                    request_deserializer=inventory__service__pb2.WebRTCSignal.FromString,
                    response_serializer=inventory__service__pb2.SignalResponse.SerializeToString,
            ),
            'WatchWebRTCSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchWebRTCSignals,
                    request_deserializer=inventory__service__pb2.WatchSignalsRequest.FromString,
                    response_serializer=inventory__service__pb2.WebRTCSignal.SerializeToString,
            ),
            'StreamVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=inventory__service__pb2.VideoFrame.FromString,
                    response_serializer=inventory__service__pb2.VideoFrame.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=inventory__service__pb2.Command.FromString,
                    response_serializer=inventory__service__pb2.CommandResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=inventory__service__pb2.EndSessionRequest.FromString,
                    response_serializer=inventory__service__pb2.EndSessionResponse.SerializeToString,
            ),
            'ProviderStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProviderStream,
                    request_deserializer=inventory__service__pb2.ProviderMessage.FromString,
                    response_serializer=inventory__service__pb2.ProviderCommand.SerializeToString,
            ),
            'ConsumerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ConsumerStream,
                    request_deserializer=inventory__service__pb2.ConsumerCommand.FromString,
                    response_serializer=inventory__service__pb2.VideoFrame.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=inventory__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=inventory__service__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.RemoteInventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.RemoteInventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteInventoryService(object):
    """Session management and video streaming service
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/CreateSession',
            inventory__service__pb2.CreateSessionRequest.SerializeToString,
            inventory__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/ListSessions',
            inventory__service__pb2.ListSessionsRequest.SerializeToString,
            inventory__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/RequestConnection',
            inventory__service__pb2.ConnectionRequest.SerializeToString,
            inventory__service__pb2.ConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchConnectionRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inventory.RemoteInventoryService/WatchConnectionRequests',
            inventory__service__pb2.WatchRequestsRequest.SerializeToString,
            inventory__service__pb2.ConnectionRequestNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/ApproveConnection',
            inventory__service__pb2.ApproveRequest.SerializeToString,
            inventory__service__pb2.ApproveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenyConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/DenyConnection',
            inventory__service__pb2.DenyRequest.SerializeToString,
            inventory__service__pb2.DenyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchApprovalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inventory.RemoteInventoryService/WatchApprovalStatus',
            inventory__service__pb2.WatchApprovalRequest.SerializeToString,
            inventory__service__pb2.ApprovalStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendWebRTCSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/SendWebRTCSignal',
            inventory__service__pb2.WebRTCSignal.SerializeToString,
            inventory__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchWebRTCSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inventory.RemoteInventoryService/WatchWebRTCSignals',
            inventory__service__pb2.WatchSignalsRequest.SerializeToString,
            inventory__service__pb2.WebRTCSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inventory.RemoteInventoryService/StreamVideo',
            inventory__service__pb2.VideoFrame.SerializeToString,
            inventory__service__pb2.VideoFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/SendCommand',
            inventory__service__pb2.Command.SerializeToString,
            inventory__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/EndSession',
            inventory__service__pb2.EndSessionRequest.SerializeToString,
            inventory__service__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProviderStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inventory.RemoteInventoryService/ProviderStream',
            inventory__service__pb2.ProviderMessage.SerializeToString,
            inventory__service__pb2.ProviderCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inventory.RemoteInventoryService/ConsumerStream',
            inventory__service__pb2.ConsumerCommand.SerializeToString,
            inventory__service__pb2.VideoFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RemoteInventoryService/Heartbeat',
            inventory__service__pb2.HeartbeatRequest.SerializeToString,
            inventory__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
